import moment from 'moment/moment';
import { HandleVisitTraineeNO, HandleVisitTraineeYES } from '../VisitTraineeBTN/VisitTraineeBTN';
import {
  DayOfWeekWrapper,
  WrapperInfoTime,
  KindTrainee,
  Clients,
} from './SortingSecondRender.styled';

const SortingSecondRender = ({
  calculateHeight,
  URLInsta,
  clientsToday0800,
  clientsToday0900,
  clientsToday1000,
  clientsToday1100,
  clientsToday1200,
  clientsToday1300,
  clientsToday1400,
  clientsToday1500,
  clientsToday1600,
  clientsToday1700,
  clientsToday1800,
  clientsToday1900,
  clientsToday2000,
  clientsNextDay0800,
  clientsNextDay0900,
  clientsNextDay1000,
  clientsNextDay1100,
  clientsNextDay1200,
  clientsNextDay1300,
  clientsNextDay1400,
  clientsNextDay1500,
  clientsNextDay1600,
  clientsNextDay1700,
  clientsNextDay1800,
  clientsNextDay1900,
  clientsNextDay2000,
  clientsNextDayTwo0800,
  clientsNextDayTwo0900,
  clientsNextDayTwo1000,
  clientsNextDayTwo1100,
  clientsNextDayTwo1200,
  clientsNextDayTwo1300,
  clientsNextDayTwo1400,
  clientsNextDayTwo1500,
  clientsNextDayTwo1600,
  clientsNextDayTwo1700,
  clientsNextDayTwo1800,
  clientsNextDayTwo1900,
  clientsNextDayTwo2000,
  clientsNextDayThree0800,
  clientsNextDayThree0900,
  clientsNextDayThree1000,
  clientsNextDayThree1100,
  clientsNextDayThree1200,
  clientsNextDayThree1300,
  clientsNextDayThree1400,
  clientsNextDayThree1500,
  clientsNextDayThree1600,
  clientsNextDayThree1700,
  clientsNextDayThree1800,
  clientsNextDayThree1900,
  clientsNextDayThree2000,
  clientsNextDayFour0800,
  clientsNextDayFour0900,
  clientsNextDayFour1000,
  clientsNextDayFour1100,
  clientsNextDayFour1200,
  clientsNextDayFour1300,
  clientsNextDayFour1400,
  clientsNextDayFour1500,
  clientsNextDayFour1600,
  clientsNextDayFour1700,
  clientsNextDayFour1800,
  clientsNextDayFour1900,
  clientsNextDayFour2000,
  clientsNextDayFive0800,
  clientsNextDayFive0900,
  clientsNextDayFive1000,
  clientsNextDayFive1100,
  clientsNextDayFive1200,
  clientsNextDayFive1300,
  clientsNextDayFive1400,
  clientsNextDayFive1500,
  clientsNextDayFive1600,
  clientsNextDayFive1700,
  clientsNextDayFive1800,
  clientsNextDayFive1900,
  clientsNextDayFive2000,
  clientsNextDaySix0800,
  clientsNextDaySix0900,
  clientsNextDaySix1000,
  clientsNextDaySix1100,
  clientsNextDaySix1200,
  clientsNextDaySix1300,
  clientsNextDaySix1400,
  clientsNextDaySix1500,
  clientsNextDaySix1600,
  clientsNextDaySix1700,
  clientsNextDaySix1800,
  clientsNextDaySix1900,
  clientsNextDaySix2000,
  nextDay2,
  nextDay3,
  nextDay4,
  nextDay5 }) => {
  const dateOfNextDay2 = moment().add(3, 'days').format('DD.MM.YYYY');
  const dateOfNextDay3 = moment().add(4, 'days').format('DD.MM.YYYY');
  const dateOfNextDay4 = moment().add(5, 'days').format('DD.MM.YYYY');
  const dateOfNextDay5 = moment().add(6, 'days').format('DD.MM.YYYY');
  // console.log(clientsToday1400);

  const VisitTrainings = ({ item }) => {
    return (
      <>
        {item.visitTrainee ?
          <>
            <HandleVisitTraineeYES item={item} />
            <a href={URLInsta({ item })} target="_blank" rel="noopener noreferrer" id={item._id} className='visitTraineeYES'>
              {item.name}
            </a>
            <HandleVisitTraineeNO item={item} />
          </>
          :
          <>
            <HandleVisitTraineeYES item={item} />
            <a href={URLInsta({ item })} target="_blank" rel="noopener noreferrer" id={item._id} className={item.canceledTraining ? 'visitTraineeNO' : ''}>
              {item.name}
            </a>
            <HandleVisitTraineeNO item={item} />
          </>}
      </>
    )
  };

const ThreeDays = ({ usersToday, usersNextDay, usersNextDayTwo, usersNextDayThree, usersNextDayFour, usersNextDayFive, usersNextDaySix }) => {
  return (
    <>
      <WrapperInfoTime style={{
        height: calculateHeight(
          usersToday.length, usersNextDay.length, usersNextDayTwo.length, usersNextDayThree.length,
          usersNextDayFour.length, usersNextDayFive.length, usersNextDaySix.length
        )
      }}>
        {/* {!showContent && <button onClick={handleClick}>Show Content</button>} */}
        {/* {!showContent && usersToday.length > 0 ? <ShowUsersBTN onClick={handleClick}>
          <KindTrainee>{usersToday[0].kind_trainee} <span style={{ color: '#23923f' }}>({usersToday.length})</span></KindTrainee></ShowUsersBTN> : null}
        {showContent && (
          <ol start={1} type={1} style={{ marginLeft: '10px' }}>
            {usersToday.length > 0 ? usersToday.map((item) => (
              <Clients key={item._id} style={{ backgroundColor: '#cac0b5' }}>
                <VisitTrainings item={item} />
              </Clients>
            )) : <p>-</p>}
          </ol>
        )} */}
        {usersToday.length > 0 ? <KindTrainee>{usersToday[0].kind_trainee} <span style={{ color: '#23923f', fontSize: '12px' }}>({usersToday.length})</span></KindTrainee> : null}
          <ol start={1} type={1} style={{ marginLeft: '10px' }}>
            {usersToday.length > 0 ? usersToday.map((item) => (
              <Clients key={item._id} style={{ backgroundColor: '#cac0b5' }}>
                <VisitTrainings item={item} />
              </Clients>
            )) : <p>-</p>}
          </ol>
      </WrapperInfoTime>
    </>
    );
  };

  return(
    <div style={{ display: 'flex', justifyContent: 'flex-start', alignItems: 'center', width: '100%' }}>
{/* ===========================NextDayThree=========================================== */}
      <div style={{ padding: '2px' }}>
        <DayOfWeekWrapper><span>{nextDay2}</span><br/><span>{dateOfNextDay2}</span></DayOfWeekWrapper>
        <ThreeDays
          usersToday={clientsNextDayThree0800}
          usersNextDay={clientsToday0800}
          usersNextDayTwo={clientsNextDay0800}
          usersNextDayThree={clientsNextDayTwo0800}
          usersNextDayFour={clientsNextDayFour0800}
          usersNextDayFive={clientsNextDayFive0800}
          usersNextDaySix={clientsNextDaySix0800}
        />
        <ThreeDays
          usersToday={clientsNextDayThree0900}
          usersNextDay={clientsToday0900}
          usersNextDayTwo={clientsNextDay0900}
          usersNextDayThree={clientsNextDayTwo0900}
          usersNextDayFour={clientsNextDayFour0900}
          usersNextDayFive={clientsNextDayFive0900}
          usersNextDaySix={clientsNextDaySix0900}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1000}
          usersNextDay={clientsToday1000}
          usersNextDayTwo={clientsNextDay1000}
          usersNextDayThree={clientsNextDayTwo1000}
          usersNextDayFour={clientsNextDayFour1000}
          usersNextDayFive={clientsNextDayFive1000}
          usersNextDaySix={clientsNextDaySix1000}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1100}
          usersNextDay={clientsToday1100}
          usersNextDayTwo={clientsNextDay1100}
          usersNextDayThree={clientsNextDayTwo1100}
          usersNextDayFour={clientsNextDayFour1100}
          usersNextDayFive={clientsNextDayFive1100}
          usersNextDaySix={clientsNextDaySix1100}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1200}
          usersNextDay={clientsToday1200}
          usersNextDayTwo={clientsNextDay1200}
          usersNextDayThree={clientsNextDayTwo1200}
          usersNextDayFour={clientsNextDayFour1200}
          usersNextDayFive={clientsNextDayFive1200}
          usersNextDaySix={clientsNextDaySix1200}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1300}
          usersNextDay={clientsToday1300}
          usersNextDayTwo={clientsNextDay1300}
          usersNextDayThree={clientsNextDayTwo1300}
          usersNextDayFour={clientsNextDayFour1300}
          usersNextDayFive={clientsNextDayFive1300}
          usersNextDaySix={clientsNextDaySix1300}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1400}
          usersNextDay={clientsToday1400}
          usersNextDayTwo={clientsNextDay1400}
          usersNextDayThree={clientsNextDayTwo1400}
          usersNextDayFour={clientsNextDayFour1400}
          usersNextDayFive={clientsNextDayFive1400}
          usersNextDaySix={clientsNextDaySix1400}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1500}
          usersNextDay={clientsToday1500}
          usersNextDayTwo={clientsNextDay1500}
          usersNextDayThree={clientsNextDayTwo1500}
          usersNextDayFour={clientsNextDayFour1500}
          usersNextDayFive={clientsNextDayFive1500}
          usersNextDaySix={clientsNextDaySix1500}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1600}
          usersNextDay={clientsToday1600}
          usersNextDayTwo={clientsNextDay1600}
          usersNextDayThree={clientsNextDayTwo1600}
          usersNextDayFour={clientsNextDayFour1600}
          usersNextDayFive={clientsNextDayFive1600}
          usersNextDaySix={clientsNextDaySix1600}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1700}
          usersNextDay={clientsToday1700}
          usersNextDayTwo={clientsNextDay1700}
          usersNextDayThree={clientsNextDayTwo1700}
          usersNextDayFour={clientsNextDayFour1700}
          usersNextDayFive={clientsNextDayFive1700}
          usersNextDaySix={clientsNextDaySix1700}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1800}
          usersNextDay={clientsToday1800}
          usersNextDayTwo={clientsNextDay1800}
          usersNextDayThree={clientsNextDayTwo1800}
          usersNextDayFour={clientsNextDayFour1800}
          usersNextDayFive={clientsNextDayFive1800}
          usersNextDaySix={clientsNextDaySix1800}
        />
        <ThreeDays
          usersToday={clientsNextDayThree1900}
          usersNextDay={clientsToday1900}
          usersNextDayTwo={clientsNextDay1900}
          usersNextDayThree={clientsNextDayTwo1900}
          usersNextDayFour={clientsNextDayFour1900}
          usersNextDayFive={clientsNextDayFive1900}
          usersNextDaySix={clientsNextDaySix1900}
        />
        <ThreeDays
          usersToday={clientsNextDayThree2000}
          usersNextDay={clientsToday2000}
          usersNextDayTwo={clientsNextDay2000}
          usersNextDayThree={clientsNextDayTwo2000}
          usersNextDayFour={clientsNextDayFour2000}
          usersNextDayFive={clientsNextDayFive2000}
          usersNextDaySix={clientsNextDaySix2000}
        />
      </div>
{/* ===========================NextDayFour======================================================================================== */}
      <div style={{ padding: '2px' }}>
        <DayOfWeekWrapper><span>{nextDay3}</span><br/><span>{dateOfNextDay3}</span></DayOfWeekWrapper>
        <ThreeDays
          usersToday={clientsNextDayFour0800}
          usersNextDay={clientsToday0800}
          usersNextDayTwo={clientsNextDay0800}
          usersNextDayThree={clientsNextDayTwo0800}
          usersNextDayFour={clientsNextDayThree0800}
          usersNextDayFive={clientsNextDayFive0800}
          usersNextDaySix={clientsNextDaySix0800}
        />
        <ThreeDays
          usersToday={clientsNextDayFour0900}
          usersNextDay={clientsToday0900}
          usersNextDayTwo={clientsNextDay0900}
          usersNextDayThree={clientsNextDayTwo0900}
          usersNextDayFour={clientsNextDayThree0900}
          usersNextDayFive={clientsNextDayFive0900}
          usersNextDaySix={clientsNextDaySix0900}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1000}
          usersNextDay={clientsToday1000}
          usersNextDayTwo={clientsNextDay1000}
          usersNextDayThree={clientsNextDayTwo1000}
          usersNextDayFour={clientsNextDayThree1000}
          usersNextDayFive={clientsNextDayFive1000}
          usersNextDaySix={clientsNextDaySix1000}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1100}
          usersNextDay={clientsToday1100}
          usersNextDayTwo={clientsNextDay1100}
          usersNextDayThree={clientsNextDayTwo1100}
          usersNextDayFour={clientsNextDayThree1100}
          usersNextDayFive={clientsNextDayFive1100}
          usersNextDaySix={clientsNextDaySix1100}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1200}
          usersNextDay={clientsToday1200}
          usersNextDayTwo={clientsNextDay1200}
          usersNextDayThree={clientsNextDayTwo1200}
          usersNextDayFour={clientsNextDayThree1200}
          usersNextDayFive={clientsNextDayFive1200}
          usersNextDaySix={clientsNextDaySix1200}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1300}
          usersNextDay={clientsToday1300}
          usersNextDayTwo={clientsNextDay1300}
          usersNextDayThree={clientsNextDayTwo1300}
          usersNextDayFour={clientsNextDayThree1300}
          usersNextDayFive={clientsNextDayFive1300}
          usersNextDaySix={clientsNextDaySix1300}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1400}
          usersNextDay={clientsToday1400}
          usersNextDayTwo={clientsNextDay1400}
          usersNextDayThree={clientsNextDayTwo1400}
          usersNextDayFour={clientsNextDayThree1400}
          usersNextDayFive={clientsNextDayFive1400}
          usersNextDaySix={clientsNextDaySix1400}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1500}
          usersNextDay={clientsToday1500}
          usersNextDayTwo={clientsNextDay1500}
          usersNextDayThree={clientsNextDayTwo1500}
          usersNextDayFour={clientsNextDayThree1500}
          usersNextDayFive={clientsNextDayFive1500}
          usersNextDaySix={clientsNextDaySix1500}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1600}
          usersNextDay={clientsToday1600}
          usersNextDayTwo={clientsNextDay1600}
          usersNextDayThree={clientsNextDayTwo1600}
          usersNextDayFour={clientsNextDayThree1600}
          usersNextDayFive={clientsNextDayFive1600}
          usersNextDaySix={clientsNextDaySix1600}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1700}
          usersNextDay={clientsToday1700}
          usersNextDayTwo={clientsNextDay1700}
          usersNextDayThree={clientsNextDayTwo1700}
          usersNextDayFour={clientsNextDayThree1700}
          usersNextDayFive={clientsNextDayFive1700}
          usersNextDaySix={clientsNextDaySix1700}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1800}
          usersNextDay={clientsToday1800}
          usersNextDayTwo={clientsNextDay1800}
          usersNextDayThree={clientsNextDayTwo1800}
          usersNextDayFour={clientsNextDayThree1800}
          usersNextDayFive={clientsNextDayFive1800}
          usersNextDaySix={clientsNextDaySix1800}
        />
        <ThreeDays
          usersToday={clientsNextDayFour1900}
          usersNextDay={clientsToday1900}
          usersNextDayTwo={clientsNextDay1900}
          usersNextDayThree={clientsNextDayTwo1900}
          usersNextDayFour={clientsNextDayThree1900}
          usersNextDayFive={clientsNextDayFive1900}
          usersNextDaySix={clientsNextDaySix1900}
        />
        <ThreeDays
          usersToday={clientsNextDayFour2000}
          usersNextDay={clientsToday2000}
          usersNextDayTwo={clientsNextDay2000}
          usersNextDayThree={clientsNextDayTwo2000}
          usersNextDayFour={clientsNextDayThree2000}
          usersNextDayFive={clientsNextDayFive2000}
          usersNextDaySix={clientsNextDaySix2000}
        />
      </div>
{/* ===========================NextDayFive======================================================================================== */}
      <div style={{ padding: '2px' }}>
        <DayOfWeekWrapper><span>{nextDay4}</span><br/><span>{dateOfNextDay4}</span></DayOfWeekWrapper>
        <ThreeDays
          usersToday={clientsNextDayFive0800}
          usersNextDay={clientsToday0800}
          usersNextDayTwo={clientsNextDay0800}
          usersNextDayThree={clientsNextDayTwo0800}
          usersNextDayFour={clientsNextDayThree0800}
          usersNextDayFive={clientsNextDayFour0800}
          usersNextDaySix={clientsNextDaySix0800}
        />
        <ThreeDays
          usersToday={clientsNextDayFive0900}
          usersNextDay={clientsToday0900}
          usersNextDayTwo={clientsNextDay0900}
          usersNextDayThree={clientsNextDayTwo0900}
          usersNextDayFour={clientsNextDayThree0900}
          usersNextDayFive={clientsNextDayFour0900}
          usersNextDaySix={clientsNextDaySix0900}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1000}
          usersNextDay={clientsToday1000}
          usersNextDayTwo={clientsNextDay1000}
          usersNextDayThree={clientsNextDayTwo1000}
          usersNextDayFour={clientsNextDayThree1000}
          usersNextDayFive={clientsNextDayFour1000}
          usersNextDaySix={clientsNextDaySix1000}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1100}
          usersNextDay={clientsToday1100}
          usersNextDayTwo={clientsNextDay1100}
          usersNextDayThree={clientsNextDayTwo1100}
          usersNextDayFour={clientsNextDayThree1100}
          usersNextDayFive={clientsNextDayFour1100}
          usersNextDaySix={clientsNextDaySix1100}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1200}
          usersNextDay={clientsToday1200}
          usersNextDayTwo={clientsNextDay1200}
          usersNextDayThree={clientsNextDayTwo1200}
          usersNextDayFour={clientsNextDayThree1200}
          usersNextDayFive={clientsNextDayFour1200}
          usersNextDaySix={clientsNextDaySix1200}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1300}
          usersNextDay={clientsToday1300}
          usersNextDayTwo={clientsNextDay1300}
          usersNextDayThree={clientsNextDayTwo1300}
          usersNextDayFour={clientsNextDayThree1300}
          usersNextDayFive={clientsNextDayFour1300}
          usersNextDaySix={clientsNextDaySix1300}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1400}
          usersNextDay={clientsToday1400}
          usersNextDayTwo={clientsNextDay1400}
          usersNextDayThree={clientsNextDayTwo1400}
          usersNextDayFour={clientsNextDayThree1400}
          usersNextDayFive={clientsNextDayFour1400}
          usersNextDaySix={clientsNextDaySix1400}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1500}
          usersNextDay={clientsToday1500}
          usersNextDayTwo={clientsNextDay1500}
          usersNextDayThree={clientsNextDayTwo1500}
          usersNextDayFour={clientsNextDayThree1500}
          usersNextDayFive={clientsNextDayFour1500}
          usersNextDaySix={clientsNextDaySix1500}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1600}
          usersNextDay={clientsToday1600}
          usersNextDayTwo={clientsNextDay1600}
          usersNextDayThree={clientsNextDayTwo1600}
          usersNextDayFour={clientsNextDayThree1600}
          usersNextDayFive={clientsNextDayFour1600}
          usersNextDaySix={clientsNextDaySix1600}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1700}
          usersNextDay={clientsToday1700}
          usersNextDayTwo={clientsNextDay1700}
          usersNextDayThree={clientsNextDayTwo1700}
          usersNextDayFour={clientsNextDayThree1700}
          usersNextDayFive={clientsNextDayFour1700}
          usersNextDaySix={clientsNextDaySix1700}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1800}
          usersNextDay={clientsToday1800}
          usersNextDayTwo={clientsNextDay1800}
          usersNextDayThree={clientsNextDayTwo1800}
          usersNextDayFour={clientsNextDayThree1800}
          usersNextDayFive={clientsNextDayFour1800}
          usersNextDaySix={clientsNextDaySix1800}
        />
        <ThreeDays
          usersToday={clientsNextDayFive1900}
          usersNextDay={clientsToday1900}
          usersNextDayTwo={clientsNextDay1900}
          usersNextDayThree={clientsNextDayTwo1900}
          usersNextDayFour={clientsNextDayThree1900}
          usersNextDayFive={clientsNextDayFour1900}
          usersNextDaySix={clientsNextDaySix1900}
        />
        <ThreeDays
          usersToday={clientsNextDayFive2000}
          usersNextDay={clientsToday2000}
          usersNextDayTwo={clientsNextDay2000}
          usersNextDayThree={clientsNextDayTwo2000}
          usersNextDayFour={clientsNextDayThree2000}
          usersNextDayFive={clientsNextDayFour2000}
          usersNextDaySix={clientsNextDaySix2000}
        />
      </div>
{/* ===========================NextDaySix======================================================================================== */}
      <div style={{ padding: '2px' }}>
        <DayOfWeekWrapper><span>{nextDay5}</span><br/><span>{dateOfNextDay5}</span></DayOfWeekWrapper>
        <ThreeDays
          usersToday={clientsNextDaySix0800}
          usersNextDay={clientsToday0800}
          usersNextDayTwo={clientsNextDay0800}
          usersNextDayThree={clientsNextDayTwo0800}
          usersNextDayFour={clientsNextDayThree0800}
          usersNextDayFive={clientsNextDayFour0800}
          usersNextDaySix={clientsNextDayFive0800}
        />
        <ThreeDays
          usersToday={clientsNextDaySix0900}
          usersNextDay={clientsToday0900}
          usersNextDayTwo={clientsNextDay0900}
          usersNextDayThree={clientsNextDayTwo0900}
          usersNextDayFour={clientsNextDayThree0900}
          usersNextDayFive={clientsNextDayFour0900}
          usersNextDaySix={clientsNextDayFive0900}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1000}
          usersNextDay={clientsToday1000}
          usersNextDayTwo={clientsNextDay1000}
          usersNextDayThree={clientsNextDayTwo1000}
          usersNextDayFour={clientsNextDayThree1000}
          usersNextDayFive={clientsNextDayFour1000}
          usersNextDaySix={clientsNextDayFive1000}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1100}
          usersNextDay={clientsToday1100}
          usersNextDayTwo={clientsNextDay1100}
          usersNextDayThree={clientsNextDayTwo1100}
          usersNextDayFour={clientsNextDayThree1100}
          usersNextDayFive={clientsNextDayFour1100}
          usersNextDaySix={clientsNextDayFive1100}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1200}
          usersNextDay={clientsToday1200}
          usersNextDayTwo={clientsNextDay1200}
          usersNextDayThree={clientsNextDayTwo1200}
          usersNextDayFour={clientsNextDayThree1200}
          usersNextDayFive={clientsNextDayFour1200}
          usersNextDaySix={clientsNextDayFive1200}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1300}
          usersNextDay={clientsToday1300}
          usersNextDayTwo={clientsNextDay1300}
          usersNextDayThree={clientsNextDayTwo1300}
          usersNextDayFour={clientsNextDayThree1300}
          usersNextDayFive={clientsNextDayFour1300}
          usersNextDaySix={clientsNextDayFive1300}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1400}
          usersNextDay={clientsToday1400}
          usersNextDayTwo={clientsNextDay1400}
          usersNextDayThree={clientsNextDayTwo1400}
          usersNextDayFour={clientsNextDayThree1400}
          usersNextDayFive={clientsNextDayFour1400}
          usersNextDaySix={clientsNextDayFive1400}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1500}
          usersNextDay={clientsToday1500}
          usersNextDayTwo={clientsNextDay1500}
          usersNextDayThree={clientsNextDayTwo1500}
          usersNextDayFour={clientsNextDayThree1500}
          usersNextDayFive={clientsNextDayFour1500}
          usersNextDaySix={clientsNextDayFive1500}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1600}
          usersNextDay={clientsToday1600}
          usersNextDayTwo={clientsNextDay1600}
          usersNextDayThree={clientsNextDayTwo1600}
          usersNextDayFour={clientsNextDayThree1600}
          usersNextDayFive={clientsNextDayFour1600}
          usersNextDaySix={clientsNextDayFive1600}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1700}
          usersNextDay={clientsToday1700}
          usersNextDayTwo={clientsNextDay1700}
          usersNextDayThree={clientsNextDayTwo1700}
          usersNextDayFour={clientsNextDayThree1700}
          usersNextDayFive={clientsNextDayFour1700}
          usersNextDaySix={clientsNextDayFive1700}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1800}
          usersNextDay={clientsToday1800}
          usersNextDayTwo={clientsNextDay1800}
          usersNextDayThree={clientsNextDayTwo1800}
          usersNextDayFour={clientsNextDayThree1800}
          usersNextDayFive={clientsNextDayFour1800}
          usersNextDaySix={clientsNextDayFive1800}
        />
        <ThreeDays
          usersToday={clientsNextDaySix1900}
          usersNextDay={clientsToday1900}
          usersNextDayTwo={clientsNextDay1900}
          usersNextDayThree={clientsNextDayTwo1900}
          usersNextDayFour={clientsNextDayThree1900}
          usersNextDayFive={clientsNextDayFour1900}
          usersNextDaySix={clientsNextDayFive1900}
        />
        <ThreeDays
          usersToday={clientsNextDaySix2000}
          usersNextDay={clientsToday2000}
          usersNextDayTwo={clientsNextDay2000}
          usersNextDayThree={clientsNextDayTwo2000}
          usersNextDayFour={clientsNextDayThree2000}
          usersNextDayFive={clientsNextDayFour2000}
          usersNextDaySix={clientsNextDayFive2000}
        />
      </div>
    </div>
  )
};

export default SortingSecondRender;